## Logistic Regression Implementation

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [4]:
# Gets the description of the dataset
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [11]:
print(dataset.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
# Convert the dataset into dataframe
import pandas as pd
import numpy as np

In [8]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [13]:
# Add the output feature in our dataframe
df['target']=dataset.target

In [14]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [15]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [16]:
df['target'].unique()

array([0, 1, 2])

Insight: The output feature has 3 values but for now we try to make it as binary classification so we take only two values for the o/p feature

In [18]:
# shows the data which has target value 0 and 1 not 2
df[df['target']!=2]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [19]:
df_copy=df[df['target']!=2]

In [20]:
df_copy['target'].unique()

array([0, 1])

In [22]:
## Independent and dependent features
X=df_copy.iloc[:,:-1] #copies all the rows and column except last column which is output into X
y=df_copy.iloc[:,-1] #Copies the last column into y

In [23]:
# Train the model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [41]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int64

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
classification=LogisticRegression(max_iter=200)

In [27]:
classification

LogisticRegression(max_iter=200)

In [28]:
classification.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [31]:
# Predict the output for the test data
y_pred=classification.predict(X_test)
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion Metrics,Accuracy,Classification Report - Precision and Recall

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [33]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [34]:
print(accuracy_score(y_test,y_pred))

1.0


Insight: Here the accuracy is showing 100 percent.

In [43]:
#Classification_report shows the recall, precision, f1-score etc.
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Cross Validation

In [44]:
from sklearn.model_selection import KFold

In [49]:
cv=KFold(n_splits=5)

In [50]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [51]:
from sklearn.model_selection import cross_val_score

In [52]:
## these are the scores all the cross validation
scores=cross_val_score(classification,X_train,y_train,scoring='accuracy',cv=cv)

In [54]:
# Average of the accuracies
np.mean(scores)

1.0

## Lets see more complex data

In [63]:
# make a prediction with a multinomial logistic regression model
# The make_classification function can be used to generate a random n-class classification problem.
# This initially creates clusters of points normally distributed (std=1).
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

In [64]:
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [66]:
complex_class_model=LogisticRegression(max_iter=200)

In [67]:
complex_class_model.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [68]:
y_pred_complex=complex_class_model.predict(X_test)

## Confusion Metrics,Accuracy,Classification Report - Precision and Recall

In [69]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [72]:
## Cross Validatiuon
cv=KFold(n_splits=5)
scores_complex=cross_val_score(complex_class_model,X_train,y_train,cv=cv)
scores_complex

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [73]:
# Average of the accuracies
np.mean(scores_complex)

0.8099999999999999