## K Nearest Neighbour Classifier

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=1000, # 1000 observations
    n_features=3, # 3 total features
     n_redundant=1,
    n_classes=2, # binary target/label
    random_state=999
)

In [3]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [4]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [9]:
y_pred=classifier.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [13]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[158  20]
 [ 11 141]]
0.906060606060606
              precision    recall  f1-score   support

           0       0.93      0.89      0.91       178
           1       0.88      0.93      0.90       152

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [12]:
## Task
GridsearchCV
for i k=1,2,3,4,5,6,7,8,9,10

## K best

SyntaxError: ignored

## KNN Regressor

In [14]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=2, noise=10, random_state=42)

In [15]:
X

array([[-0.16711808,  0.14671369],
       [-0.02090159,  0.11732738],
       [ 0.15041891,  0.364961  ],
       ...,
       [ 0.30263547, -0.75427585],
       [ 0.38193545,  0.43004165],
       [ 0.07736831, -0.8612842 ]])

In [16]:
y

array([-1.49969499e+01, -1.26780889e+01,  1.77754545e+01,  6.66146467e+00,
       -1.41955300e+01, -2.52448482e+01, -3.92316263e+01, -5.20180382e+01,
        5.76368853e+00, -5.01186029e+01,  3.68932300e+01, -5.73879093e+01,
       -1.43015904e+01, -3.14639243e+01,  3.73110627e+01,  1.56178696e+01,
       -6.66080007e+00, -4.89229382e+01, -9.58772599e+00,  8.53715394e+01,
        1.66537460e+01, -3.41293946e+01, -3.72378063e+01, -4.87281315e+01,
       -5.51790322e+01, -3.55366169e+01, -3.72747912e+00,  7.34218222e+01,
        1.01718119e+02, -1.90116475e+01, -3.43901341e+01, -9.62943086e+00,
        1.16658030e+01,  2.08905862e+01, -1.70900105e+01, -1.50447947e+01,
        4.68228521e+01, -1.89552845e+01,  5.71898896e+01, -5.48067724e+01,
       -5.16310769e+01, -8.08939793e+00,  6.06663511e+01,  3.55254095e+01,
        1.04233163e+01, -4.30586696e+01,  1.12998389e+00,  2.31342762e+01,
       -6.13582958e+00,  2.60353115e+01,  5.87540393e+01,  2.13374470e+01,
       -4.73477124e+01,  

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [18]:
from sklearn.neighbors import KNeighborsRegressor

In [20]:
regressor=KNeighborsRegressor(n_neighbors=6,algorithm='auto')
regressor.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=6)

In [22]:
y_pred=regressor.predict(X_test)

In [23]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [24]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.9189275159979495
9.009462452972217
127.45860414317289
