## Part 1

Numpy - Numerical Array

In [48]:
import numpy as np

In [49]:
l = [1,2,3,4,5]

In [50]:
arr = np.array(l)

In [51]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [7]:
arr.ndim

1

In [8]:
arr1.ndim

2

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
mat = np.matrix(l)

In [12]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [13]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
a = arr

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[0] = 100

In [19]:
arr

array([100,   2,   3,   4,   5])

In [20]:
a

array([100,   2,   3,   4,   5])

In [21]:
b = np.copy(arr)

In [22]:
b

array([100,   2,   3,   4,   5])

In [23]:
b[0] = 234

In [24]:
b

array([234,   2,   3,   4,   5])

In [25]:
arr

array([100,   2,   3,   4,   5])

In [26]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [29]:
iterable  = (i*i for i in range(5))

In [30]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('23 45 56',sep  = ' ' )

array([23., 45., 56.])

In [32]:
np.fromstring('23,45,56',sep  = ',' )

array([23., 45., 56.])

In [33]:
arr

array([100,   2,   3,   4,   5])

In [34]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [35]:
arr.ndim

1

In [36]:
arr1.ndim

2

In [37]:
arr.size

5

In [40]:
arr1.size

6

In [41]:
arr.shape

(5,)

In [42]:
arr1.shape

(2, 3)

In [43]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [44]:
arr.dtype

dtype('int64')

In [45]:
arr1.dtype

dtype('int64')

## Part 2

In [52]:
import numpy as np

In [53]:
list(range(5))

[0, 1, 2, 3, 4]

In [54]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
list(range(0.4,10.4))

TypeError: ignored

In [56]:
list(np.arange(.4 , 10.4 , 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [57]:
np.linspace(1,5 , 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [59]:
np.logspace(1,5 , 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [63]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [64]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [65]:
arr = np.ones((3,4))

In [66]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [68]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [69]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [70]:
np.empty((2,5))

array([[ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186],
       [ 9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ]])

In [71]:
arr1 = np.eye(5)

In [72]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
#Convert the arrays into data frame
import pandas as pd

In [74]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [76]:
np.random.rand(2,3)

array([[0.43457855, 0.82280472, 0.91034532],
       [0.70466238, 0.5818523 , 0.7308131 ]])

In [77]:
np.random.randn(2,3)

array([[-1.20630563,  0.03643556, -0.27351763],
       [-0.12160169,  0.09398085,  1.91405701]])

In [78]:
arr2 = np.random.randint(1,5 , (3,4))

In [79]:
arr2

array([[2, 3, 2, 3],
       [3, 4, 1, 2],
       [3, 3, 3, 3]])

In [80]:
arr2.size

12

In [81]:
arr2.shape

(3, 4)

In [82]:
arr2.reshape(6,2)

array([[2, 3],
       [2, 3],
       [3, 4],
       [1, 2],
       [3, 3],
       [3, 3]])

In [83]:
arr2.reshape(2,6)

array([[2, 3, 2, 3, 3, 4],
       [1, 2, 3, 3, 3, 3]])

In [84]:
arr2.reshape(4,3)

array([[2, 3, 2],
       [3, 3, 4],
       [1, 2, 3],
       [3, 3, 3]])

In [85]:
arr2.reshape(4,-1)

array([[2, 3, 2],
       [3, 3, 4],
       [1, 2, 3],
       [3, 3, 3]])

In [86]:
arr2.reshape(4,-1432453453)

array([[2, 3, 2],
       [3, 3, 4],
       [1, 2, 3],
       [3, 3, 3]])

In [87]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[2]]],


         [[[3]]],


         [[[2]]]],



        [[[[3]]],


         [[[3]]],


         [[[4]]]]],




       [[[[[1]]],


         [[[2]]],


         [[[3]]]],



        [[[[3]]],


         [[[3]]],


         [[[3]]]]]])

In [88]:
arr1 = np.random.randint(1,10 , (5,6))

In [89]:
arr1

array([[4, 5, 8, 2, 6, 2],
       [9, 8, 8, 9, 6, 3],
       [8, 6, 3, 2, 7, 7],
       [4, 5, 3, 3, 6, 5],
       [2, 9, 7, 1, 3, 1]])

In [90]:
arr1 >8

array([[False, False, False, False, False, False],
       [ True, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False]])

In [91]:
arr1[arr1 >8]

array([9, 9, 9])

In [92]:
arr1

array([[4, 5, 8, 2, 6, 2],
       [9, 8, 8, 9, 6, 3],
       [8, 6, 3, 2, 7, 7],
       [4, 5, 3, 3, 6, 5],
       [2, 9, 7, 1, 3, 1]])

In [93]:
arr1[0,[0,1]]

array([4, 5])

In [94]:
arr1[2:4 , [2,3]]

array([[3, 2],
       [3, 3]])

In [95]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [96]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 1]])

In [97]:
arr2

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [98]:
arr1+arr2

array([[2, 4, 3],
       [2, 3, 3],
       [4, 2, 3]])

In [99]:
arr1-arr2

array([[ 0,  0,  1],
       [ 0,  1, -1],
       [ 0,  0, -1]])

In [100]:
arr1*arr2

array([[1, 4, 2],
       [1, 2, 2],
       [4, 1, 2]])

In [101]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 1]])

In [102]:
arr2

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [103]:
arr1@arr2

array([[7, 6, 9],
       [5, 5, 7],
       [5, 6, 6]])

In [104]:
arr1/arr2

array([[1. , 1. , 2. ],
       [1. , 2. , 0.5],
       [1. , 1. , 0.5]])

In [105]:
arr1/0

<ipython-input-105-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [106]:
#Numpy – Broadcasting.

In [107]:
arr = np.zeros((3,4))

In [108]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [110]:
a = np.array([1,2,3,4])

In [111]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [112]:
b = np.array([[3,4,5]])

In [113]:
#Transpose
arr1 = arr+b.T

In [114]:
b.T

array([[3],
       [4],
       [5]])

In [115]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [116]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [117]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [118]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [119]:
np.min(arr1)

3.0

In [120]:
np.max(arr1)

5.0