## Part 3

In [1]:
import numpy as np

In [2]:
#Numpy - Array Manipulation.

In [3]:
arr = np.random.randint(1,10 , (4,4))

In [4]:
arr

array([[5, 6, 1, 3],
       [2, 7, 7, 5],
       [9, 5, 8, 4],
       [3, 4, 6, 5]])

In [5]:
arr.reshape(8,2)

array([[5, 6],
       [1, 3],
       [2, 7],
       [7, 5],
       [9, 5],
       [8, 4],
       [3, 4],
       [6, 5]])

In [6]:
arr

array([[5, 6, 1, 3],
       [2, 7, 7, 5],
       [9, 5, 8, 4],
       [3, 4, 6, 5]])

In [7]:
arr.T

array([[5, 2, 9, 3],
       [6, 7, 5, 4],
       [1, 7, 8, 6],
       [3, 5, 4, 5]])

In [8]:
arr.flatten()

array([5, 6, 1, 3, 2, 7, 7, 5, 9, 5, 8, 4, 3, 4, 6, 5])

In [9]:
arr

array([[5, 6, 1, 3],
       [2, 7, 7, 5],
       [9, 5, 8, 4],
       [3, 4, 6, 5]])

In [10]:
np.expand_dims(arr,axis=1)

array([[[5, 6, 1, 3]],

       [[2, 7, 7, 5]],

       [[9, 5, 8, 4]],

       [[3, 4, 6, 5]]])

In [11]:
np.expand_dims(arr,axis=0)

array([[[5, 6, 1, 3],
        [2, 7, 7, 5],
        [9, 5, 8, 4],
        [3, 4, 6, 5]]])

In [12]:
data = np.array([[1] , [2] , [3]])

In [13]:
np.squeeze(data)

array([1, 2, 3])

In [14]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [15]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [16]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
#Numpy - Binary Operators

In [18]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [19]:
arr1

array([[8, 1, 6, 7],
       [4, 9, 3, 3],
       [8, 9, 4, 9]])

In [20]:
arr2

array([[2, 3, 4, 7],
       [7, 7, 6, 4],
       [2, 5, 5, 1]])

In [21]:
arr1+arr2

array([[10,  4, 10, 14],
       [11, 16,  9,  7],
       [10, 14,  9, 10]])

In [22]:
arr1*arr2

array([[16,  3, 24, 49],
       [28, 63, 18, 12],
       [16, 45, 20,  9]])

In [23]:
arr1/arr2

array([[4.        , 0.33333333, 1.5       , 1.        ],
       [0.57142857, 1.28571429, 0.5       , 0.75      ],
       [4.        , 1.8       , 0.8       , 9.        ]])

In [24]:
arr1-arr2

array([[ 6, -2,  2,  0],
       [-3,  2, -3, -1],
       [ 6,  4, -1,  8]])

In [25]:
arr1**arr2

array([[     64,       1,    1296,  823543],
       [  16384, 4782969,     729,      81],
       [     64,   59049,    1024,       9]])

In [26]:
~arr1

array([[ -9,  -2,  -7,  -8],
       [ -5, -10,  -4,  -4],
       [ -9, -10,  -5, -10]])

In [27]:
arr1

array([[8, 1, 6, 7],
       [4, 9, 3, 3],
       [8, 9, 4, 9]])

In [28]:
arr1>arr2

array([[ True, False,  True, False],
       [False,  True, False, False],
       [ True,  True, False,  True]])

In [29]:
#Numpy - String Functions.

In [30]:
arr = np.array(["sudh" , "kumar"])

In [31]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [32]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [33]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [34]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [35]:
#Numpy - Mathematical Functions.

In [36]:
arr1

array([[8, 1, 6, 7],
       [4, 9, 3, 3],
       [8, 9, 4, 9]])

In [37]:
np.sin(arr1)

array([[ 0.98935825,  0.84147098, -0.2794155 ,  0.6569866 ],
       [-0.7568025 ,  0.41211849,  0.14112001,  0.14112001],
       [ 0.98935825,  0.41211849, -0.7568025 ,  0.41211849]])

In [38]:
np.cos(arr1)

array([[-0.14550003,  0.54030231,  0.96017029,  0.75390225],
       [-0.65364362, -0.91113026, -0.9899925 , -0.9899925 ],
       [-0.14550003, -0.91113026, -0.65364362, -0.91113026]])

In [39]:
np.tan(arr1)

array([[-6.79971146,  1.55740772, -0.29100619,  0.87144798],
       [ 1.15782128, -0.45231566, -0.14254654, -0.14254654],
       [-6.79971146, -0.45231566,  1.15782128, -0.45231566]])

In [40]:
np.log10(arr1)

array([[0.90308999, 0.        , 0.77815125, 0.84509804],
       [0.60205999, 0.95424251, 0.47712125, 0.47712125],
       [0.90308999, 0.95424251, 0.60205999, 0.95424251]])

In [41]:
np.exp(arr1)

array([[2.98095799e+03, 2.71828183e+00, 4.03428793e+02, 1.09663316e+03],
       [5.45981500e+01, 8.10308393e+03, 2.00855369e+01, 2.00855369e+01],
       [2.98095799e+03, 8.10308393e+03, 5.45981500e+01, 8.10308393e+03]])

In [42]:
np.power(arr1,2)

array([[64,  1, 36, 49],
       [16, 81,  9,  9],
       [64, 81, 16, 81]])

In [43]:
np.mean(arr1)

5.916666666666667

In [44]:
np.median(arr1)

6.5

In [45]:
np.std(arr1)

2.691292543659191

In [47]:
np.var(arr1)

7.243055555555556

In [48]:
np.min(arr1)

1

In [49]:
np.max(arr1)

9

In [51]:
#Numpy - Arithmetic Operations.

In [52]:
arr1

array([[8, 1, 6, 7],
       [4, 9, 3, 3],
       [8, 9, 4, 9]])

In [53]:
arr2

array([[2, 3, 4, 7],
       [7, 7, 6, 4],
       [2, 5, 5, 1]])

In [54]:
arr1-arr2

array([[ 6, -2,  2,  0],
       [-3,  2, -3, -1],
       [ 6,  4, -1,  8]])

In [55]:
np.subtract(arr1,arr2)

array([[ 6, -2,  2,  0],
       [-3,  2, -3, -1],
       [ 6,  4, -1,  8]])

In [56]:
np.multiply(arr1,arr2)

array([[16,  3, 24, 49],
       [28, 63, 18, 12],
       [16, 45, 20,  9]])

In [57]:
np.mod(arr1,arr2)

array([[0, 1, 2, 0],
       [4, 2, 3, 3],
       [0, 4, 4, 0]])

In [58]:
np.power(arr1,arr2)

array([[     64,       1,    1296,  823543],
       [  16384, 4782969,     729,      81],
       [     64,   59049,    1024,       9]])

In [59]:
np.sqrt(arr1)

array([[2.82842712, 1.        , 2.44948974, 2.64575131],
       [2.        , 3.        , 1.73205081, 1.73205081],
       [2.82842712, 3.        , 2.        , 3.        ]])

In [60]:
#Numpy - Statistical Functions.

In [61]:
arr1

array([[8, 1, 6, 7],
       [4, 9, 3, 3],
       [8, 9, 4, 9]])

In [62]:
np.mean(arr1)

5.916666666666667

In [63]:
np.std(arr1)

2.691292543659191

In [64]:
np.median(arr1)

6.5

## Part 4

In [65]:
##Sort, Search & Counting Functions.

In [67]:
import numpy as np

In [69]:
arr = np.array([4,2,8,5,3,9,12,56])

In [70]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [71]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [72]:
np.searchsorted(arr,6)

5

In [73]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [74]:
np.count_nonzero(arr1)

6

In [75]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9]),)

In [76]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [77]:
#Numpy - Byte Swapping.

In [78]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [79]:
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [80]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [81]:
#Numpy - Copies &Views.

In [82]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [83]:
a = np.copy(arr1)

In [84]:
b = arr1.view()

In [85]:
b = arr1

In [86]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [87]:
b[0] = 234

In [88]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [89]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [91]:
#Numpy - Matrix Library.

In [93]:
import numpy.matlib as nm

In [95]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [96]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [97]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [98]:
#Numpy - Linear Algebra

In [100]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [102]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [103]:
arr1

array([[0, 1],
       [2, 1]])

In [104]:
arr2

array([[1, 0],
       [1, 2]])

In [106]:
np.dot(arr1,arr2)

array([[1, 2],
       [3, 2]])

In [107]:
arr1@arr2

array([[1, 2],
       [3, 2]])